spring:
  datasource:
    url: jdbc:mysql://52.79.174.201:3306/DB이름?characterEncoding=utf8
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp

mybatis:
  type-aliases-package: com.joshua.mapper
  mapper-locations: mybatis/mapper/**/*.xml

